name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-22.04", "windows-2022", "macos-12"]
        scala: ["2.12", "2.13", "3"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
    - name: Mount caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
    - name: Compile and test
      run: |
       sbt "++ ${{ matrix.scala }}.x" test
      shell: bash
    - name: Format check
      if: ${{ runner.os == 'Linux' }}
      run: |
        sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
  # Single final job for mergify.
  ci-passed:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: ':'
